### ISSUE TITLE
Adjust conformation pop up behavior 

### ISSUE THREAD

**Issue by katlukens** [Turkosaurus/nailivic#12]
Have conformation of part production display where user is in page. Or return more slowly to previous position. 

Here is how to make a fixed header. Try this.
[link](https://www.tutorialrepublic.com/faq/how-to-create-fixed-header-or-footer-using-css.php)

**Comment by turkosaurus** [comment]
Since the main navbar for bootstrap is `<nav class="navbar navbar-default navbar-expand-sm fixed-top">` ... maybe we could just shove the `flash()` inside a `<nav class=" ... fixed-bottom">`?

**Comment by turkosaurus** [comment]
Wait, that's for turkosaur.us. There's some weird shit going on with an id tag [here](https://github.com/Turkosaurus/nailivic/blob/b69d41ae292a594614c1f8684bf921f36e5f4fcc/templates/layout.html#L37)? I'm sorry. 🙃

**Comment by turkosaurus** [comment]
implemented in v1.3.0 fixes
